/* Auto-generated by Zynk Effect connector - DO NOT EDIT */
/* Generated: 2026-05-11T20:35:28.611259 */

import {
  Effect,
  Schema,
  Stream,
} from "effect"
import {
  callCommand,
  callChannel,
  type CallOptions,
  type ZynkClient,
  type ZynkError,
} from "./_effect_internal"
export {
  ZynkClient,
  initZynk,
  layerZynkClient,
  type CallOptions,
  type RetryOptions,
  type BackoffStrategy,
  type ZynkClientConfig,
  type ZynkError,
  ZynkNetworkError,
  ZynkHttpError,
  ZynkTimeoutError,
  ZynkDecodeError,
  ZynkAbortError,
  ZynkStreamError,
  ZynkUploadError,
} from "./_effect_internal"

// ============ Schemas ============

export const Tick = Schema.Struct({
  n: Schema.Number,
  label: Schema.String
})

export type Tick = Schema.Schema.Type<typeof Tick>

export const User = Schema.Struct({
  id: Schema.Number,
  name: Schema.String,
  isAdmin: Schema.UndefinedOr(Schema.Boolean)
})

export type User = Schema.Schema.Type<typeof User>

// ============ Commands ============

/**
 * Return a single user by id.
 */
export const getUser = (args: { userId: number }, options?: CallOptions): Effect.Effect<User, ZynkError, ZynkClient> =>
  callCommand("get_user", { user_id: args.userId }, User, options)

/**
 * List all users.
 */
export const listUsers = (args: { activeOnly?: boolean }, options?: CallOptions): Effect.Effect<ReadonlyArray<User>, ZynkError, ZynkClient> =>
  callCommand("list_users", { active_only: args.activeOnly }, Schema.Array(User), options)

// ============ Channels ============

/**
 * Stream ten ticks to demonstrate Effect Streams.
 */
export const streamTicks = (args: { label: string }, options?: CallOptions): Stream.Stream<Tick, ZynkError, ZynkClient> =>
  callChannel("stream_ticks", { label: args.label }, Tick, options)
