//! Minimal TypeScript code printer with indentation support.
//!
//! Endpoint emission is implemented in a later feature. This module currently
//! provides the formatting foundation and model type emission needed by the
//! lowering scaffold tests.

use zynk_schema::{ApiGraph, Field};

use crate::lowering;

/// Print a minimal generated `api.ts` source for an API graph.
pub fn print_api(graph: &ApiGraph) -> String {
    let mut printer = TsPrinter::new();
    printer.line("// Generated by zynk-gen-ts. Do not edit.");
    printer.line("import { initBridge } from \"./_internal\";");
    printer.blank_line();
    printer.line("export { initBridge };");

    if !graph.models.is_empty() {
        printer.blank_line();
        for model in graph.models.values() {
            if let Some(doc) = &model.doc {
                printer.doc(doc);
            }
            printer.line(format!(
                "export interface {} {{",
                crate::naming::to_pascal_case(&model.name)
            ));
            printer.indented(|printer| {
                for field in &model.fields {
                    print_field(printer, field, graph);
                }
            });
            printer.line("}");
            printer.blank_line();
        }
    }

    printer.finish()
}

fn print_field(printer: &mut TsPrinter, field: &Field, graph: &ApiGraph) {
    if let Some(doc) = &field.doc {
        printer.doc(doc);
    }

    let ty = lowering::apply_optional_nullable(
        lowering::lower_required_with_graph(&field.ty, graph),
        field.optional,
        field.nullable,
    );
    printer.line(format!("{}: {ty};", field.wire_name));
}

/// Small indentation-aware TypeScript source printer.
#[derive(Debug, Default)]
pub struct TsPrinter {
    output: String,
    indent: usize,
}

impl TsPrinter {
    /// Create an empty printer.
    pub fn new() -> Self {
        Self::default()
    }

    /// Append a line at the current indentation level.
    pub fn line(&mut self, line: impl AsRef<str>) {
        let line = line.as_ref();
        if !line.is_empty() {
            for _ in 0..self.indent {
                self.output.push_str("    ");
            }
            self.output.push_str(line);
        }
        self.output.push('\n');
    }

    /// Append a blank line.
    pub fn blank_line(&mut self) {
        self.output.push('\n');
    }

    /// Append a JSDoc comment.
    pub fn doc(&mut self, doc: &str) {
        self.line("/**");
        for line in doc.lines() {
            self.line(format!(" * {line}"));
        }
        self.line(" */");
    }

    /// Run a closure with one additional indentation level.
    pub fn indented(&mut self, write: impl FnOnce(&mut Self)) {
        self.indent += 1;
        write(self);
        self.indent -= 1;
    }

    /// Finish and return the printed source.
    pub fn finish(self) -> String {
        self.output
    }
}

#[cfg(test)]
mod tests {
    use zynk_schema::{ApiGraph, EnumDef, Field, ModelDef, TypeRef, Value};

    use super::{print_api, TsPrinter};

    macro_rules! json {
        ($value:literal) => {
            Value::from($value)
        };
    }

    #[test]
    fn printer_indents_blocks() {
        let mut printer = TsPrinter::new();
        printer.line("export interface User {");
        printer.indented(|printer| printer.line("name: string;"));
        printer.line("}");

        assert_eq!(
            printer.finish(),
            "export interface User {\n    name: string;\n}\n"
        );
    }

    #[test]
    fn prints_representative_model_with_literal_enum_optional_nullable() {
        let mut graph = ApiGraph::new();
        let mut enum_def = EnumDef::new("priority");
        enum_def.values = vec![json!("low"), json!("high")];
        graph.insert_enum(enum_def);

        let mut model = ModelDef::new("task");
        model.doc = Some("A task model.".to_string());
        model.fields.push(Field::new(
            "title",
            "title",
            TypeRef::primitive("string"),
            true,
        ));
        let mut literal = TypeRef::literal(json!("todo"));
        literal.optional = true;
        model
            .fields
            .push(Field::new("state", "state", literal, false));
        let mut maybe_priority = TypeRef::enum_ref("priority");
        maybe_priority.nullable = true;
        let mut field = Field::new("priority", "priority", maybe_priority, false);
        field.nullable = true;
        model.fields.push(field);
        graph.insert_model(model);

        let output = print_api(&graph);

        assert!(output.contains("/**\n * A task model.\n */\nexport interface Task"));
        assert!(output.contains("    title: string;"));
        assert!(output.contains("    state: \"todo\" | undefined;"));
        assert!(output.contains("    priority: \"low\" | \"high\" | null;"));
        assert!(!output.contains("?:"));
    }
}
