/* Auto-generated by Zynk - DO NOT EDIT */
/* Effect connector runtime - see https://effect.website */

import {
  Context,
  Data,
  Duration,
  Effect,
  Layer,
  ManagedRuntime,
  Schedule,
  Schema,
  Stream,
} from "effect"

// ---------------------------------------------------------------------------
// Tagged errors
// ---------------------------------------------------------------------------

export class ZynkNetworkError extends Data.TaggedError("ZynkNetworkError")<{
  readonly url: string
  readonly cause: unknown
}> {}

export class ZynkHttpError extends Data.TaggedError("ZynkHttpError")<{
  readonly url: string
  readonly status: number
  readonly statusText: string
  readonly code?: string
  readonly message?: string
  readonly details?: unknown
}> {}

export class ZynkTimeoutError extends Data.TaggedError("ZynkTimeoutError")<{
  readonly url: string
  readonly durationMs: number
}> {}

export class ZynkDecodeError extends Data.TaggedError("ZynkDecodeError")<{
  readonly url: string
  readonly cause: unknown
}> {}

export class ZynkAbortError extends Data.TaggedError("ZynkAbortError")<{
  readonly url: string
}> {}

export class ZynkStreamError extends Data.TaggedError("ZynkStreamError")<{
  readonly url: string
  readonly code: string
  readonly message: string
  readonly details?: unknown
}> {}

export class ZynkUploadError extends Data.TaggedError("ZynkUploadError")<{
  readonly handler: string
  readonly status?: number
  readonly code?: string
  readonly message: string
  readonly details?: unknown
}> {}

export type ZynkError =
  | ZynkNetworkError
  | ZynkHttpError
  | ZynkTimeoutError
  | ZynkDecodeError
  | ZynkAbortError
  | ZynkStreamError
  | ZynkUploadError

// ---------------------------------------------------------------------------
// Retry / backoff configuration
// ---------------------------------------------------------------------------

export type DurationInput = Duration.DurationInput

export type BackoffStrategy =
  | { readonly kind: "none" }
  | { readonly kind: "fixed"; readonly delay: DurationInput }
  | { readonly kind: "spaced"; readonly delay: DurationInput }
  | {
      readonly kind: "exponential"
      readonly base: DurationInput
      readonly factor?: number
      readonly max?: DurationInput
    }

export interface RetryOptions {
  readonly times?: number
  readonly backoff?: BackoffStrategy
  readonly jitter?: boolean
  readonly while?: (error: ZynkError) => boolean
  readonly until?: (error: ZynkError) => boolean
}

const DEFAULT_RETRY: RetryOptions = {
  times: 0,
  backoff: {
    kind: "exponential",
    base: "200 millis",
    factor: 2,
    max: "5 seconds",
  },
  jitter: true,
  while: (error) =>
    error._tag === "ZynkNetworkError" ||
    error._tag === "ZynkTimeoutError" ||
    (error._tag === "ZynkHttpError" && error.status >= 500),
}

const buildSchedule = (
  options: RetryOptions,
): Schedule.Schedule<unknown, ZynkError, never> => {
  const backoff = options.backoff ?? DEFAULT_RETRY.backoff!
  let policy: Schedule.Schedule<unknown, ZynkError, never>

  switch (backoff.kind) {
    case "none":
      policy = Schedule.recurs(0) as unknown as Schedule.Schedule<
        unknown,
        ZynkError,
        never
      >
      break
    case "fixed":
      policy = Schedule.fixed(backoff.delay) as unknown as Schedule.Schedule<
        unknown,
        ZynkError,
        never
      >
      break
    case "spaced":
      policy = Schedule.spaced(backoff.delay) as unknown as Schedule.Schedule<
        unknown,
        ZynkError,
        never
      >
      break
    case "exponential": {
      let exp = Schedule.exponential(
        backoff.base,
        backoff.factor,
      ) as unknown as Schedule.Schedule<unknown, ZynkError, never>
      if (backoff.max !== undefined) {
        exp = Schedule.intersect(exp, Schedule.spaced(backoff.max))
      }
      policy = exp
      break
    }
  }

  const times = options.times ?? DEFAULT_RETRY.times ?? 0
  policy = Schedule.intersect(policy, Schedule.recurs(times))

  if (options.jitter ?? DEFAULT_RETRY.jitter) {
    policy = Schedule.jittered(policy)
  }

  const whileFn = options.while ?? DEFAULT_RETRY.while
  const untilFn = options.until
  if (whileFn || untilFn) {
    policy = Schedule.whileInput(policy, (error: ZynkError) => {
      if (untilFn && untilFn(error)) return false
      if (whileFn && !whileFn(error)) return false
      return true
    })
  }

  return policy
}

const mergeRetry = (
  base: RetryOptions | undefined,
  overrides: RetryOptions | undefined,
): RetryOptions => ({
  times: overrides?.times ?? base?.times ?? DEFAULT_RETRY.times,
  backoff: overrides?.backoff ?? base?.backoff ?? DEFAULT_RETRY.backoff,
  jitter: overrides?.jitter ?? base?.jitter ?? DEFAULT_RETRY.jitter,
  while: overrides?.while ?? base?.while ?? DEFAULT_RETRY.while,
  until: overrides?.until ?? base?.until,
})

// ---------------------------------------------------------------------------
// Client configuration / service
// ---------------------------------------------------------------------------

export interface ZynkClientConfig {
  readonly baseUrl: string
  readonly timeout?: DurationInput
  readonly retry?: RetryOptions
  readonly headers?: Readonly<Record<string, string>>
  readonly fetch?: typeof globalThis.fetch
}

export interface CallOptions {
  readonly timeout?: DurationInput
  readonly retry?: RetryOptions
  readonly signal?: AbortSignal
  readonly headers?: Readonly<Record<string, string>>
}

export interface ZynkClientShape extends ZynkClientConfig {
  readonly resolvedFetch: typeof globalThis.fetch
}

export class ZynkClient extends Context.Tag("ZynkClient")<
  ZynkClient,
  ZynkClientShape
>() {}

export const layerZynkClient = (
  config: ZynkClientConfig,
): Layer.Layer<ZynkClient> =>
  Layer.succeed(ZynkClient, {
    ...config,
    resolvedFetch:
      config.fetch ?? globalThis.fetch.bind(globalThis),
  })

export const initZynk = (config: ZynkClientConfig): Layer.Layer<ZynkClient> => {
  const layer = layerZynkClient(config)
  setDefaultLayer(layer)
  return layer
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const buildHeaders = (
  base: Readonly<Record<string, string>> | undefined,
  call: Readonly<Record<string, string>> | undefined,
  contentType?: string,
): Record<string, string> => {
  const headers: Record<string, string> = {
    ...(base ?? {}),
    ...(call ?? {}),
  }
  if (
    contentType &&
    !("Content-Type" in headers) &&
    !("content-type" in headers)
  ) {
    headers["Content-Type"] = contentType
  }
  return headers
}

const joinUrl = (base: string, path: string): string => {
  const trimmedBase = base.replace(/\/$/, "")
  const trimmedPath = path.startsWith("/") ? path : `/${path}`
  return `${trimmedBase}${trimmedPath}`
}

const linkSignals = (
  caller: AbortSignal | undefined,
  inner: AbortController,
): (() => void) | undefined => {
  if (!caller) return undefined
  if (caller.aborted) {
    inner.abort()
    return undefined
  }
  const onAbort = () => inner.abort()
  caller.addEventListener("abort", onAbort, { once: true })
  return () => caller.removeEventListener("abort", onAbort)
}

const wrapNetworkError = (url: string, cause: unknown): ZynkError => {
  if (cause instanceof DOMException && cause.name === "AbortError") {
    return new ZynkAbortError({ url })
  }
  if (
    typeof cause === "object" &&
    cause !== null &&
    "name" in cause &&
    (cause as { name?: string }).name === "AbortError"
  ) {
    return new ZynkAbortError({ url })
  }
  return new ZynkNetworkError({ url, cause })
}

const safeJsonParse = (
  text: string,
): {
  result?: unknown
  code?: string
  message?: string
  details?: unknown
  error?: string
} => {
  try {
    return JSON.parse(text)
  } catch {
    return { message: text }
  }
}

const camelToSnake = (key: string): string =>
  key.replace(/[A-Z]/g, (m, i) => (i === 0 ? m.toLowerCase() : `_${m.toLowerCase()}`))

const toSnakeCaseKeys = (value: unknown): unknown => {
  if (Array.isArray(value)) return value.map(toSnakeCaseKeys)
  if (value !== null && typeof value === "object") {
    const out: Record<string, unknown> = {}
    for (const [key, v] of Object.entries(value as Record<string, unknown>)) {
      out[camelToSnake(key)] = toSnakeCaseKeys(v)
    }
    return out
  }
  return value
}

// ---------------------------------------------------------------------------
// RPC calls
// ---------------------------------------------------------------------------

export const callCommand = <A, I>(
  command: string,
  args: unknown,
  responseSchema: Schema.Schema<A, I>,
  options?: CallOptions,
): Effect.Effect<A, ZynkError, ZynkClient> =>
  Effect.gen(function* () {
    const client = yield* ZynkClient
    const url = joinUrl(client.baseUrl, `/command/${command}`)
    const timeout = options?.timeout ?? client.timeout
    const retry = mergeRetry(client.retry, options?.retry)

    const performRequest = Effect.gen(function* () {
      const controller = new AbortController()
      const unlink = linkSignals(options?.signal, controller)

      const response = yield* Effect.tryPromise({
        try: () =>
          client.resolvedFetch(url, {
            method: "POST",
            headers: buildHeaders(
              client.headers,
              options?.headers,
              "application/json",
            ),
            body: JSON.stringify(toSnakeCaseKeys(args) ?? {}),
            signal: controller.signal,
          }),
        catch: (cause) => wrapNetworkError(url, cause),
      }).pipe(Effect.ensuring(Effect.sync(() => unlink?.())))

      const text = yield* Effect.tryPromise({
        try: () => response.text(),
        catch: (cause) => new ZynkNetworkError({ url, cause }),
      })

      const payload = text.length > 0 ? safeJsonParse(text) : {}

      if (!response.ok) {
        return yield* Effect.fail(
          new ZynkHttpError({
            url,
            status: response.status,
            statusText: response.statusText,
            code: payload.code,
            message: payload.message,
            details: payload.details,
          }),
        )
      }

      return yield* Schema.decodeUnknown(responseSchema)(
        payload.result,
      ).pipe(
        Effect.mapError((cause) => new ZynkDecodeError({ url, cause })),
      )
    })

    const withTimeout = timeout
      ? performRequest.pipe(
          Effect.timeoutFail({
            duration: timeout,
            onTimeout: () =>
              new ZynkTimeoutError({
                url,
                durationMs: Duration.toMillis(Duration.decode(timeout)),
              }),
          }),
        )
      : performRequest

    return yield* withTimeout.pipe(Effect.retry(buildSchedule(retry)))
  })

// ---------------------------------------------------------------------------
// Channels: server-sent events as Effect Streams
// ---------------------------------------------------------------------------

interface OpenedStream {
  readonly response: Response
  readonly controller: AbortController
  readonly unlink: (() => void) | undefined
}

export const callChannel = <A, I>(
  command: string,
  args: unknown,
  itemSchema: Schema.Schema<A, I>,
  options?: CallOptions,
): Stream.Stream<A, ZynkError, ZynkClient> =>
  Stream.unwrap(
    Effect.gen(function* () {
      const client = yield* ZynkClient
      const url = joinUrl(client.baseUrl, `/channel/${command}`)
      const timeout = options?.timeout ?? client.timeout

      const open: Effect.Effect<OpenedStream, ZynkError> = Effect.gen(
        function* () {
          const controller = new AbortController()
          const unlink = linkSignals(options?.signal, controller)

          const response = yield* Effect.tryPromise({
            try: () =>
              client.resolvedFetch(url, {
                method: "POST",
                headers: buildHeaders(
                  client.headers,
                  options?.headers,
                  "application/json",
                ),
                body: JSON.stringify(toSnakeCaseKeys(args) ?? {}),
                signal: controller.signal,
              }),
            catch: (cause) => {
              unlink?.()
              return wrapNetworkError(url, cause)
            },
          })

          if (!response.ok) {
            unlink?.()
            const text = yield* Effect.tryPromise({
              try: () => response.text(),
              catch: () =>
                new ZynkNetworkError({ url, cause: "stream open" }),
            })
            const payload = text ? safeJsonParse(text) : {}
            return yield* Effect.fail(
              new ZynkHttpError({
                url,
                status: response.status,
                statusText: response.statusText,
                code: payload.code,
                message: payload.message,
                details: payload.details,
              }),
            )
          }

          if (!response.body) {
            unlink?.()
            return yield* Effect.fail(
              new ZynkStreamError({
                url,
                code: "NO_STREAM",
                message: "Response has no body",
              }),
            )
          }

          return { response, controller, unlink }
        },
      )

      const opened: OpenedStream = yield* (timeout
        ? open.pipe(
            Effect.timeoutFail({
              duration: timeout,
              onTimeout: () =>
                new ZynkTimeoutError({
                  url,
                  durationMs: Duration.toMillis(Duration.decode(timeout)),
                }),
            }),
          )
        : open)

      return makeSseStream(url, opened.response.body!, itemSchema).pipe(
        Stream.ensuring(
          Effect.sync(() => {
            opened.unlink?.()
            opened.controller.abort()
          }),
        ),
      )
    }),
  )

const makeSseStream = <A, I>(
  url: string,
  body: ReadableStream<Uint8Array>,
  itemSchema: Schema.Schema<A, I>,
): Stream.Stream<A, ZynkError> =>
  Stream.async<A, ZynkError>((emit) => {
    const reader = body.getReader()
    const decoder = new TextDecoder()
    let buffer = ""
    let stopped = false

    const stop = async () => {
      if (stopped) return
      stopped = true
      try {
        await reader.cancel()
      } catch {
        // ignore
      }
    }

    const pump = async () => {
      try {
        while (!stopped) {
          const { done, value } = await reader.read()
          if (done) {
            void emit.end()
            return
          }
          buffer += decoder.decode(value, { stream: true })
          const events = buffer.split("\n\n")
          buffer = events.pop() ?? ""
          for (const block of events) {
            if (!block.trim()) continue
            let eventType = "message"
            let eventData = ""
            for (const line of block.split("\n")) {
              if (line.startsWith("event: ")) eventType = line.slice(7)
              else if (line.startsWith("data: ")) eventData = line.slice(6)
            }
            if (eventType === "error") {
              const parsed = eventData ? safeJsonParse(eventData) : {}
              void emit.fail(
                new ZynkStreamError({
                  url,
                  code:
                    typeof parsed.code === "string"
                      ? parsed.code
                      : "STREAM_ERROR",
                  message:
                    typeof parsed.message === "string"
                      ? parsed.message
                      : parsed.error ?? "stream error",
                  details: parsed.details,
                }),
              )
              return
            }
            if (eventType === "close") {
              void emit.end()
              return
            }
            if (eventData) {
              const parsed = safeJsonParse(eventData)
              const payload =
                parsed && typeof parsed === "object" && !Array.isArray(parsed)
                  ? { event: eventType, ...parsed }
                  : parsed
              try {
                const decoded = await Effect.runPromise(
                  Schema.decodeUnknown(itemSchema)(payload) as Effect.Effect<A>,
                )
                void emit.single(decoded)
              } catch (cause) {
                void emit.fail(
                  new ZynkDecodeError({ url, cause }),
                )
                return
              }
            }
          }
        }
      } catch (cause) {
        if (!stopped) {
          void emit.fail(wrapNetworkError(url, cause))
        }
      }
    }

    void pump()

    return Effect.sync(() => {
      void stop()
    })
  })

// ---------------------------------------------------------------------------
// Uploads
// ---------------------------------------------------------------------------

export interface UploadProgressEvent {
  readonly loaded: number
  readonly total: number
  readonly percentage: number
}

export interface UploadOptions extends CallOptions {
  readonly onProgress?: (event: UploadProgressEvent) => void
}

export const callUpload = <A, I>(
  handler: string,
  files: ReadonlyArray<File>,
  args: Record<string, unknown>,
  responseSchema: Schema.Schema<A, I>,
  options?: UploadOptions,
): Effect.Effect<A, ZynkError, ZynkClient> =>
  Effect.gen(function* () {
    const client = yield* ZynkClient
    const url = joinUrl(client.baseUrl, `/upload/${handler}`)
    const timeout = options?.timeout ?? client.timeout
    const retry = mergeRetry(client.retry, options?.retry)

    const perform = Effect.async<A, ZynkError>((resume) => {
      const xhr = new XMLHttpRequest()
      let aborted = false
      const onCallerAbort = () => {
        aborted = true
        try {
          xhr.abort()
        } catch {
          // ignore
        }
      }
      if (options?.signal) {
        if (options.signal.aborted) {
          onCallerAbort()
        } else {
          options.signal.addEventListener("abort", onCallerAbort, {
            once: true,
          })
        }
      }
      const unlink = () => {
        options?.signal?.removeEventListener("abort", onCallerAbort)
      }

      const formData = new FormData()
      for (const file of files) {
        formData.append("files", file)
      }
      formData.append("_args", JSON.stringify(toSnakeCaseKeys(args) ?? {}))

      if (options?.onProgress) {
        xhr.upload.onprogress = (event) => {
          if (event.lengthComputable) {
            options.onProgress!({
              loaded: event.loaded,
              total: event.total,
              percentage: Math.round((event.loaded / event.total) * 100),
            })
          }
        }
      }

      xhr.onload = () => {
        unlink()
        const text = xhr.responseText
        const payload = text ? safeJsonParse(text) : {}
        if (xhr.status >= 200 && xhr.status < 300) {
          Effect.runPromiseExit(
            Schema.decodeUnknown(responseSchema)(payload.result) as Effect.Effect<A, unknown>,
          ).then((exit) => {
            if (exit._tag === "Success") {
              resume(Effect.succeed(exit.value))
            } else {
              resume(
                Effect.fail(
                  new ZynkDecodeError({ url, cause: exit.cause }),
                ),
              )
            }
          })
        } else {
          resume(
            Effect.fail(
              new ZynkUploadError({
                handler,
                status: xhr.status,
                code: payload.code,
                message:
                  payload.message ??
                  `Upload failed with status ${xhr.status}`,
                details: payload.details,
              }),
            ),
          )
        }
      }
      xhr.onerror = () => {
        unlink()
        if (aborted) {
          resume(Effect.fail(new ZynkAbortError({ url })))
        } else {
          resume(
            Effect.fail(
              new ZynkUploadError({
                handler,
                message: "Upload network error",
              }),
            ),
          )
        }
      }
      xhr.onabort = () => {
        unlink()
        resume(Effect.fail(new ZynkAbortError({ url })))
      }

      const headers = buildHeaders(client.headers, options?.headers)
      xhr.open("POST", url)
      for (const [key, value] of Object.entries(headers)) {
        if (key.toLowerCase() === "content-type") continue
        xhr.setRequestHeader(key, value)
      }
      xhr.send(formData)

      return Effect.sync(() => {
        try {
          xhr.abort()
        } catch {
          // ignore
        }
      })
    })

    const withTimeout = timeout
      ? perform.pipe(
          Effect.timeoutFail({
            duration: timeout,
            onTimeout: () =>
              new ZynkTimeoutError({
                url,
                durationMs: Duration.toMillis(Duration.decode(timeout)),
              }),
          }),
        )
      : perform

    return yield* withTimeout.pipe(Effect.retry(buildSchedule(retry)))
  })

// ---------------------------------------------------------------------------
// Static helpers
// ---------------------------------------------------------------------------

export const buildStaticUrl = (
  handler: string,
  params: Record<string, unknown>,
): Effect.Effect<string, never, ZynkClient> =>
  Effect.gen(function* () {
    const client = yield* ZynkClient
    const search = new URLSearchParams()
    for (const [key, value] of Object.entries(params)) {
      if (value === undefined || value === null) continue
      search.set(key, String(value))
    }
    const qs = search.toString()
    const suffix = qs ? `?${qs}` : ""
    return joinUrl(client.baseUrl, `/static/${handler}${suffix}`)
  })

// ---------------------------------------------------------------------------
// WebSocket helper
// ---------------------------------------------------------------------------

export interface WsMessage<E extends string = string, D = unknown> {
  readonly event: E
  readonly data: D
}

export const wsUrl = (
  handler: string,
): Effect.Effect<string, never, ZynkClient> =>
  Effect.gen(function* () {
    const client = yield* ZynkClient
    const base = client.baseUrl.replace(/^http/, "ws")
    return joinUrl(base, `/ws/${handler}`)
  })

export const openWebSocket = (
  handler: string,
): Effect.Effect<WebSocket, ZynkNetworkError, ZynkClient> =>
  Effect.gen(function* () {
    const url = yield* wsUrl(handler)
    return yield* Effect.try({
      try: () => new WebSocket(url),
      catch: (cause) => new ZynkNetworkError({ url, cause }),
    })
  })

// ---------------------------------------------------------------------------
// Promise surface helpers
// ---------------------------------------------------------------------------

let _defaultRuntime: ManagedRuntime.ManagedRuntime<ZynkClient, never> | undefined

export const setDefaultLayer = (layer: Layer.Layer<ZynkClient>): void => {
  if (_defaultRuntime) {
    void _defaultRuntime.dispose()
  }
  _defaultRuntime = ManagedRuntime.make(layer)
}

const requireRuntime = (): ManagedRuntime.ManagedRuntime<ZynkClient, never> => {
  if (!_defaultRuntime) {
    throw new Error(
      "Zynk: call initZynk(config) before using promise-style functions.",
    )
  }
  return _defaultRuntime
}

export const runPromise = <A>(
  effect: Effect.Effect<A, ZynkError, ZynkClient>,
): Promise<A> => requireRuntime().runPromise(effect)

export const toAsyncIterable = <A>(
  stream: Stream.Stream<A, ZynkError, ZynkClient>,
): AsyncIterable<A> => ({
  async *[Symbol.asyncIterator]() {
    const rt = await requireRuntime().runtime()
    const inner = Stream.toAsyncIterableRuntime(stream, rt)
    for await (const item of inner) {
      yield item
    }
  },
})

export const disposeZynk = (): Promise<void> => {
  const rt = _defaultRuntime
  _defaultRuntime = undefined
  return rt ? rt.dispose() : Promise.resolve()
}
