//! Effect-TS generator scaffold for Zynk API graphs.

pub mod lowering;
pub mod options;
pub mod runtime;
pub mod topological;
pub mod types;

use std::path::PathBuf;

use options::EffectGeneratorOptions;
use zynk_codegen::{GeneratedFile, GenerationContext, GenerationResult, Generator};
use zynk_schema::ApiGraph;

/// Generate Effect client files with default options.
pub fn generate(graph: &ApiGraph) -> GenerationResult {
    generate_with_options(graph, &EffectGeneratorOptions::default())
}

/// Generate Effect client files with explicit options.
pub fn generate_with_options(
    graph: &ApiGraph,
    _options: &EffectGeneratorOptions,
) -> GenerationResult {
    let api = print_scaffold_api(graph);
    GenerationResult::new(vec![
        GeneratedFile::new(PathBuf::from("api.ts"), api),
        GeneratedFile::new(
            PathBuf::from("_effect_internal.ts"),
            runtime::effect_internal_ts(),
        ),
    ])
}

fn print_scaffold_api(graph: &ApiGraph) -> String {
    let mut sections = vec![
        "/* Auto-generated by Zynk Effect connector - DO NOT EDIT */".to_string(),
        "import { Schema } from \"effect\"".to_string(),
    ];

    let schemas = lowering::render_model_schemas(graph);
    if !schemas.is_empty() {
        sections.push(format!(
            "// ============ Schemas ============\n\n{}",
            schemas.join("\n\n")
        ));
    }

    format!("{}\n", sections.join("\n\n"))
}

/// Concrete generator implementation for the Effect target.
#[derive(Debug, Default, Clone, Copy)]
pub struct EffectGenerator;

impl EffectGenerator {
    /// Create an Effect generator.
    pub fn new() -> Self {
        Self
    }
}

impl Generator for EffectGenerator {
    fn generate(&self, ctx: &GenerationContext) -> GenerationResult {
        let options = EffectGeneratorOptions::from_mapping(ctx.options).unwrap_or_default();
        generate_with_options(ctx.graph, &options)
    }
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use zynk_schema::{ApiGraph, Field, ModelDef, TypeRef};

    #[test]
    fn generate_returns_api_and_embedded_effect_runtime_files() {
        let result = super::generate(&ApiGraph::new());

        assert_eq!(result.files.len(), 2);
        assert_eq!(result.files[0].path, PathBuf::from("api.ts"));
        assert_eq!(result.files[1].path, PathBuf::from("_effect_internal.ts"));
        assert!(result.files[0]
            .contents
            .contains("Auto-generated by Zynk Effect connector"));
        assert!(result.files[1]
            .contents
            .contains("export const callCommand"));
    }

    #[test]
    fn scaffold_api_includes_lowered_schema_structs() {
        let mut graph = ApiGraph::new();
        let mut user = ModelDef::new("User");
        user.fields.push(Field::new(
            "name",
            "name",
            TypeRef::primitive("string"),
            true,
        ));
        graph.insert_model(user);

        let result = super::generate(&graph);

        assert!(result.files[0]
            .contents
            .contains("export const User = Schema.Struct"));
        assert!(result.files[0].contents.contains("name: Schema.String"));
    }
}
