"""Lower the Zynk API graph into a TypeScript module."""

from __future__ import annotations

from datetime import datetime
from typing import Any

from zynk.core.ir import ApiGraph

from .legacy import TypeScriptGenerator
from .ts_ast import TsExport, TsImport, TsModule, TsRaw


class TypeScriptLowerer:
    def __init__(self, generator: TypeScriptGenerator | None = None):
        self.generator = generator or TypeScriptGenerator()

    def lower(
        self,
        graph: ApiGraph,
        legacy: Any,
    ) -> TsModule:
        commands = legacy.get_all_commands()
        uploads = legacy.get_all_uploads()
        statics = legacy.get_all_statics()
        message_handlers = legacy.get_all_message_handlers()
        models = legacy.get_all_models()

        module = TsModule(
            banner=f"""/* Auto-generated by Zynk - DO NOT EDIT */
/* Generated: {datetime.now().isoformat()} */"""
        )

        imports = ["initBridge", "BridgeRequestError"]
        type_imports = ["BridgeError"]
        if commands:
            imports.append("request")
            if any(endpoint.kind == "channel" for endpoint in graph.endpoints.values()):
                imports.append("createChannel")
                type_imports.append("BridgeChannel")
        if uploads:
            imports.append("createUpload")
            type_imports.extend(["UploadHandle", "UploadProgressEvent"])
        if message_handlers or statics:
            imports.append("getBaseUrl")

        module.add(TsImport(imports, "./_internal"))
        module.add(TsImport(type_imports, "./_internal", type_only=True))
        module.add(TsExport(["initBridge", "BridgeRequestError"]))
        module.add(TsExport(type_imports, type_only=True))

        models_to_generate: set[str] = set()
        command_functions = [
            self.generator._generate_command_function(cmd, models_to_generate)
            for cmd in sorted(commands.values(), key=lambda c: c.name)
        ]

        for model_name in models:
            models_to_generate.add(model_name)

        generated_models: set[str] = set()
        model_interfaces: list[str] = []
        self._collect_models(models, models_to_generate, generated_models, model_interfaces)

        upload_functions = [
            self.generator._generate_upload_function(upload, models_to_generate)
            for upload in sorted(uploads.values(), key=lambda u: u.name)
        ]
        self._collect_models(models, models_to_generate, generated_models, model_interfaces)

        static_functions = [
            self.generator._generate_static_function(static, models_to_generate)
            for static in sorted(statics.values(), key=lambda s: s.name)
        ]
        websocket_classes = [
            self.generator._generate_websocket_class(handler, models_to_generate)
            for handler in sorted(message_handlers.values(), key=lambda h: h.name)
        ]
        self._collect_models(models, models_to_generate, generated_models, model_interfaces)

        if model_interfaces:
            module.add(TsRaw("// ============ Interfaces ============\n\n" + "\n\n".join(model_interfaces)))
        if command_functions:
            module.add(TsRaw("// ============ Commands ============\n\n" + "\n\n".join(command_functions)))
        if upload_functions:
            module.add(TsRaw("// ============ Uploads ============\n\n" + "\n\n".join(upload_functions)))
        if static_functions:
            module.add(TsRaw("// ============ Static Files ============\n\n" + "\n\n".join(static_functions)))
        if websocket_classes:
            module.add(TsRaw("// ============ WebSockets ============\n\n" + "\n\n".join(websocket_classes)))

        return module

    def _collect_models(
        self,
        models: dict[str, Any],
        models_to_generate: set[str],
        generated_models: set[str],
        model_interfaces: list[str],
    ) -> None:
        while models_to_generate - generated_models:
            current_batch = models_to_generate - generated_models
            for model_name in sorted(current_batch):
                model = models.get(model_name)
                if model:
                    model_interfaces.append(
                        self.generator._generate_model_interface(model, models_to_generate)
                    )
                generated_models.add(model_name)
