import React, { useState } from 'react';
import UsersDemo from './components/UsersDemo';
import WeatherDemo from './components/WeatherDemo';
import TasksDemo from './components/TasksDemo';

type Tab = 'users' | 'weather' | 'tasks';

const App: React.FC = () => {
  const [activeTab, setActiveTab] = useState<Tab>('users');

  return (
    <div style={styles.container}>
      <header style={styles.header}>
        <h1 style={styles.title}>🌉 Zynk Kitchen Sink</h1>
        <p style={styles.subtitle}>
          Demonstrating type-safe Python ↔ TypeScript communication
        </p>
      </header>

      <nav style={styles.nav}>
        <button
          style={{
            ...styles.tab,
            ...(activeTab === 'users' ? styles.activeTab : {}),
          }}
          onClick={() => setActiveTab('users')}
        >
          👥 Users
        </button>
        <button
          style={{
            ...styles.tab,
            ...(activeTab === 'weather' ? styles.activeTab : {}),
          }}
          onClick={() => setActiveTab('weather')}
        >
          🌤️ Weather
        </button>
        <button
          style={{
            ...styles.tab,
            ...(activeTab === 'tasks' ? styles.activeTab : {}),
          }}
          onClick={() => setActiveTab('tasks')}
        >
          ✅ Tasks
        </button>
      </nav>

      <main style={styles.main}>
        {activeTab === 'users' && <UsersDemo />}
        {activeTab === 'weather' && <WeatherDemo />}
        {activeTab === 'tasks' && <TasksDemo />}
      </main>

      <footer style={styles.footer}>
        <p>
          TypeScript client auto-generated by Zynk • Hot-reload enabled
        </p>
      </footer>
    </div>
  );
};

const styles: Record<string, React.CSSProperties> = {
  container: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '20px',
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
  },
  header: {
    textAlign: 'center',
    marginBottom: '30px',
  },
  title: {
    fontSize: '2.5rem',
    marginBottom: '10px',
    color: '#2c3e50',
  },
  subtitle: {
    fontSize: '1.1rem',
    color: '#7f8c8d',
  },
  nav: {
    display: 'flex',
    gap: '10px',
    marginBottom: '20px',
    borderBottom: '2px solid #e0e0e0',
    paddingBottom: '10px',
  },
  tab: {
    padding: '12px 24px',
    fontSize: '1rem',
    border: 'none',
    background: '#fff',
    borderRadius: '8px 8px 0 0',
    cursor: 'pointer',
    transition: 'all 0.2s',
    color: '#666',
  },
  activeTab: {
    background: '#3498db',
    color: '#fff',
  },
  main: {
    flex: 1,
    background: '#fff',
    borderRadius: '8px',
    padding: '20px',
    boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
  },
  footer: {
    textAlign: 'center',
    marginTop: '20px',
    padding: '20px',
    color: '#95a5a6',
    fontSize: '0.9rem',
  },
};

export default App;
