/* Auto-generated by Zynk Effect connector - DO NOT EDIT */

import {
  Effect,
  Schema,
  Stream,
} from "effect"

import {
  callCommand,
  callChannel,
  callUpload,
  buildStaticUrl,
  openWebSocket,
  type CallOptions,
  type UploadOptions,
  type ZynkClient,
  type ZynkError,
  ZynkNetworkError,
} from "./_effect_internal"

export {
  ZynkClient,
  initZynk,
  layerZynkClient,
  disposeZynk,
  type CallOptions,
  type UploadOptions,
  type UploadProgressEvent,
  type RetryOptions,
  type BackoffStrategy,
  type ZynkClientConfig,
  type ZynkError,
  ZynkNetworkError,
  ZynkHttpError,
  ZynkTimeoutError,
  ZynkDecodeError,
  ZynkAbortError,
  ZynkStreamError,
  ZynkUploadError,
  toAsyncIterable,
} from "./_effect_internal"

// ============ Schemas ============

export const ChatMessage = Schema.Struct({
  user: Schema.String,
  text: Schema.String,
  timestamp: Schema.String
})

export type ChatMessage = Schema.Schema.Type<typeof ChatMessage>

export const DocumentUploadResult = Schema.Struct({
  id: Schema.String,
  filename: Schema.String,
  size: Schema.Number,
  pageCount: Schema.optionalWith(Schema.Number, { nullable: true }).pipe(Schema.fromKey("page_count"))
})

export type DocumentUploadResult = Schema.Schema.Type<typeof DocumentUploadResult>

export const FileInfo = Schema.Struct({
  id: Schema.String,
  filename: Schema.String,
  size: Schema.Number,
  contentType: Schema.propertySignature(Schema.String).pipe(Schema.fromKey("content_type")),
  checksum: Schema.String,
  uploadedAt: Schema.propertySignature(Schema.String).pipe(Schema.fromKey("uploaded_at"))
})

export type FileInfo = Schema.Schema.Type<typeof FileInfo>

export const ImageUploadResult = Schema.Struct({
  id: Schema.String,
  filename: Schema.String,
  width: Schema.optionalWith(Schema.Number, { nullable: true }),
  height: Schema.optionalWith(Schema.Number, { nullable: true }),
  thumbnailBase64: Schema.optionalWith(Schema.String, { nullable: true }).pipe(Schema.fromKey("thumbnail_base64"))
})

export type ImageUploadResult = Schema.Schema.Type<typeof ImageUploadResult>

export const ServerStatus = Schema.Struct({
  connectedUsers: Schema.propertySignature(Schema.Number).pipe(Schema.fromKey("connected_users")),
  uptimeSeconds: Schema.propertySignature(Schema.Number).pipe(Schema.fromKey("uptime_seconds"))
})

export type ServerStatus = Schema.Schema.Type<typeof ServerStatus>

export const TaskLabel = Schema.Struct({
  id: Schema.Number,
  name: Schema.String,
  color: Schema.UndefinedOr(Schema.String)
})

export type TaskLabel = Schema.Schema.Type<typeof TaskLabel>

export const Task = Schema.Struct({
  id: Schema.Number,
  title: Schema.String,
  description: Schema.optionalWith(Schema.String, { nullable: true }),
  priority: Schema.UndefinedOr(Schema.Literal("low", "medium", "high", "urgent")),
  status: Schema.UndefinedOr(Schema.Literal("todo", "in_progress", "done", "cancelled")),
  labels: Schema.UndefinedOr(Schema.Array(TaskLabel)),
  createdAt: Schema.propertySignature(Schema.String).pipe(Schema.fromKey("created_at")),
  dueDate: Schema.optionalWith(Schema.String, { nullable: true }).pipe(Schema.fromKey("due_date")),
  assignedTo: Schema.optionalWith(Schema.Number, { nullable: true }).pipe(Schema.fromKey("assigned_to"))
})

export type Task = Schema.Schema.Type<typeof Task>

export const TaskStats = Schema.Struct({
  total: Schema.Number,
  todo: Schema.Number,
  inProgress: Schema.propertySignature(Schema.Number).pipe(Schema.fromKey("in_progress")),
  done: Schema.Number,
  cancelled: Schema.Number,
  byPriority: Schema.propertySignature(Schema.Record({ key: Schema.String, value: Schema.Number })).pipe(Schema.fromKey("by_priority"))
})

export type TaskStats = Schema.Schema.Type<typeof TaskStats>

export const TaskWireCheck = Schema.Struct({
  kind: Schema.Literal("task_wire_check"),
  priority: Schema.Literal("low", "medium", "high", "urgent"),
  status: Schema.Literal("todo", "in_progress", "done", "cancelled"),
  numericStatus: Schema.propertySignature(Schema.Literal(1, 2, 3)).pipe(Schema.fromKey("numeric_status"))
})

export type TaskWireCheck = Schema.Schema.Type<typeof TaskWireCheck>

export const TypingIndicator = Schema.Struct({
  user: Schema.String,
  isTyping: Schema.propertySignature(Schema.Boolean).pipe(Schema.fromKey("is_typing"))
})

export type TypingIndicator = Schema.Schema.Type<typeof TypingIndicator>

export const User = Schema.Struct({
  id: Schema.Number,
  name: Schema.String,
  email: Schema.String,
  isActive: Schema.propertySignature(Schema.UndefinedOr(Schema.Boolean)).pipe(Schema.fromKey("is_active"))
})

export type User = Schema.Schema.Type<typeof User>

export const UserJoined = Schema.Struct({
  user: Schema.String,
  timestamp: Schema.String
})

export type UserJoined = Schema.Schema.Type<typeof UserJoined>

export const UserLeft = Schema.Struct({
  user: Schema.String,
  timestamp: Schema.String
})

export type UserLeft = Schema.Schema.Type<typeof UserLeft>

export const WeatherData = Schema.Struct({
  city: Schema.String,
  temperature: Schema.Number,
  humidity: Schema.Number,
  conditions: Schema.String,
  windSpeed: Schema.propertySignature(Schema.Number).pipe(Schema.fromKey("wind_speed"))
})

export type WeatherData = Schema.Schema.Type<typeof WeatherData>

export const WeatherForecast = Schema.Struct({
  day: Schema.String,
  high: Schema.Number,
  low: Schema.Number,
  conditions: Schema.String,
  precipitationChance: Schema.propertySignature(Schema.Number).pipe(Schema.fromKey("precipitation_chance"))
})

export type WeatherForecast = Schema.Schema.Type<typeof WeatherForecast>

export const WeatherUpdate = Schema.Struct({
  timestamp: Schema.String,
  city: Schema.String,
  temperature: Schema.Number,
  conditions: Schema.String
})

export type WeatherUpdate = Schema.Schema.Type<typeof WeatherUpdate>

// ============ Commands ============

/**
 * Create a new label.
 */
export const createLabel = (args: { name: string; color?: string }, options?: CallOptions): Effect.Effect<TaskLabel, ZynkError, ZynkClient> =>
  callCommand("create_label", { name: args.name, color: args.color }, TaskLabel, options)

/**
 * Create a new task.
 */
export const createTask = (args: { title: string; description?: string | null; priority?: string; dueDate?: string | null; labelIds?: ReadonlyArray<number> | null }, options?: CallOptions): Effect.Effect<Task, ZynkError, ZynkClient> =>
  callCommand("create_task", { title: args.title, description: args.description, priority: args.priority, due_date: args.dueDate, label_ids: args.labelIds }, Task, options)

/**
 * Create a new user.
 * 
 * Returns the created user with their assigned ID.
 */
export const createUser = (args: { name: string; email: string }, options?: CallOptions): Effect.Effect<User, ZynkError, ZynkClient> =>
  callCommand("create_user", { name: args.name, email: args.email }, User, options)

/**
 * Delete a task.
 */
export const deleteTask = (args: { taskId: number }, options?: CallOptions): Effect.Effect<boolean, ZynkError, ZynkClient> =>
  callCommand("delete_task", { task_id: args.taskId }, Schema.Boolean, options)

/**
 * Delete a user.
 * 
 * Returns True if the user was deleted, False if they didn't exist.
 */
export const deleteUser = (args: { userId: number }, options?: CallOptions): Effect.Effect<boolean, ZynkError, ZynkClient> =>
  callCommand("delete_user", { user_id: args.userId }, Schema.Boolean, options)

/**
 * Echo a literal and enum payload without coercing wire values.
 */
export const echoTaskWireCheck = (args: { payload: TaskWireCheck }, options?: CallOptions): Effect.Effect<TaskWireCheck, ZynkError, ZynkClient> =>
  callCommand("echo_task_wire_check", { payload: Schema.encodeUnknownSync(TaskWireCheck)(args.payload) }, TaskWireCheck, options)

/**
 * Get weather forecast for a city.
 * 
 * Returns a list of forecasts for the specified number of days.
 */
export const getForecast = (args: { city: string; days?: number }, options?: CallOptions): Effect.Effect<ReadonlyArray<WeatherForecast>, ZynkError, ZynkClient> =>
  callCommand("get_forecast", { city: args.city, days: args.days }, Schema.Array(WeatherForecast), options)

/**
 * Get a task by ID.
 */
export const getTask = (args: { taskId: number }, options?: CallOptions): Effect.Effect<Task, ZynkError, ZynkClient> =>
  callCommand("get_task", { task_id: args.taskId }, Task, options)

/**
 * Get statistics about all tasks.
 */
export const getTaskStats = (options?: CallOptions): Effect.Effect<TaskStats, ZynkError, ZynkClient> =>
  callCommand("get_task_stats", {}, TaskStats, options)

/**
 * Return a canonical literal and enum payload.
 */
export const getTaskWireCheck = (options?: CallOptions): Effect.Effect<TaskWireCheck, ZynkError, ZynkClient> =>
  callCommand("get_task_wire_check", {}, TaskWireCheck, options)

/**
 * Get a user by ID.
 * 
 * Raises an error if the user doesn't exist.
 */
export const getUser = (args: { userId: number }, options?: CallOptions): Effect.Effect<User, ZynkError, ZynkClient> =>
  callCommand("get_user", { user_id: args.userId }, User, options)

/**
 * Get current weather for a city.
 * 
 * Returns simulated weather data.
 */
export const getWeather = (args: { city: string }, options?: CallOptions): Effect.Effect<WeatherData, ZynkError, ZynkClient> =>
  callCommand("get_weather", { city: args.city }, WeatherData, options)

/**
 * Get list of available cities with weather data.
 */
export const listCities = (options?: CallOptions): Effect.Effect<ReadonlyArray<string>, ZynkError, ZynkClient> =>
  callCommand("list_cities", {}, Schema.Array(Schema.String), options)

/**
 * Get all available labels.
 */
export const listLabels = (options?: CallOptions): Effect.Effect<ReadonlyArray<TaskLabel>, ZynkError, ZynkClient> =>
  callCommand("list_labels", {}, Schema.Array(TaskLabel), options)

/**
 * List tasks with optional filters.
 * 
 * Can filter by status, priority, or label.
 */
export const listTasks = (args: { status?: string | null; priority?: string | null; labelId?: number | null }, options?: CallOptions): Effect.Effect<ReadonlyArray<Task>, ZynkError, ZynkClient> =>
  callCommand("list_tasks", { status: args.status, priority: args.priority, label_id: args.labelId }, Schema.Array(Task), options)

/**
 * List all users.
 * 
 * Optionally filter to only active users.
 */
export const listUsers = (args: { activeOnly?: boolean }, options?: CallOptions): Effect.Effect<ReadonlyArray<User>, ZynkError, ZynkClient> =>
  callCommand("list_users", { active_only: args.activeOnly }, Schema.Array(User), options)

/**
 * Search for users by name or email.
 * 
 * Returns users whose name or email contains the search query.
 */
export const searchUsers = (args: { query: string }, options?: CallOptions): Effect.Effect<ReadonlyArray<User>, ZynkError, ZynkClient> =>
  callCommand("search_users", { query: args.query }, Schema.Array(User), options)

/**
 * Update the status of a task.
 */
export const updateTaskStatus = (args: { taskId: number; status: string }, options?: CallOptions): Effect.Effect<Task, ZynkError, ZynkClient> =>
  callCommand("update_task_status", { task_id: args.taskId, status: args.status }, Task, options)

/**
 * Update an existing user.
 * 
 * Only provided fields will be updated.
 */
export const updateUser = (args: { userId: number; name?: string | null; email?: string | null; isActive?: boolean | null }, options?: CallOptions): Effect.Effect<User, ZynkError, ZynkClient> =>
  callCommand("update_user", { user_id: args.userId, name: args.name, email: args.email, is_active: args.isActive }, User, options)

// ============ Channels ============

/**
 * Stream weather updates for multiple cities.
 * 
 * Cycles through the provided cities, sending one update every 2 seconds.
 */
export const streamMultiCity = (args: { cities: ReadonlyArray<string> }, options?: CallOptions): Stream.Stream<WeatherUpdate, ZynkError, ZynkClient> =>
  callChannel("stream_multi_city", { cities: args.cities }, WeatherUpdate, options)

/**
 * Stream live weather updates for a city.
 * 
 * This demonstrates Zynk's streaming/channel support.
 * Updates are sent at the specified interval until the channel is closed.
 * 
 * Args:
 * city: The city to monitor.
 * interval_seconds: How often to send updates (1-60 seconds).
 * channel: The streaming channel (automatically injected).
 */
export const streamWeather = (args: { city: string; intervalSeconds: number }, options?: CallOptions): Stream.Stream<WeatherUpdate, ZynkError, ZynkClient> =>
  callChannel("stream_weather", { city: args.city, interval_seconds: args.intervalSeconds }, WeatherUpdate, options)

// ============ Uploads ============

/**
 * Upload a document (PDF, DOC, DOCX).
 * 
 * Only accepts document files up to 10MB.
 */
export const uploadDocument = (args: { file: File; extractMetadata?: boolean }, options?: UploadOptions): Effect.Effect<DocumentUploadResult, ZynkError, ZynkClient> =>
  callUpload("upload_document", [args.file], { extract_metadata: args.extractMetadata }, DocumentUploadResult, options)

/**
 * Upload a single file of any type.
 * 
 * Returns file information including a checksum.
 */
export const uploadFile = (args: { file: File }, options?: UploadOptions): Effect.Effect<FileInfo, ZynkError, ZynkClient> =>
  callUpload("upload_file", [args.file], {}, FileInfo, options)

/**
 * Upload multiple files at once.
 * 
 * Returns information about all uploaded files.
 */
export const uploadFiles = (args: { files: ReadonlyArray<File> }, options?: UploadOptions): Effect.Effect<ReadonlyArray<FileInfo>, ZynkError, ZynkClient> =>
  callUpload("upload_files", args.files, {}, Schema.Array(FileInfo), options)

/**
 * Upload an image file with optional thumbnail generation.
 * 
 * Only accepts image files up to 5MB.
 */
export const uploadImage = (args: { file: File; generateThumbnail?: boolean }, options?: UploadOptions): Effect.Effect<ImageUploadResult, ZynkError, ZynkClient> =>
  callUpload("upload_image", [args.file], { generate_thumbnail: args.generateThumbnail }, ImageUploadResult, options)

/**
 * Upload multiple media files (images, videos, audio).
 * 
 * Accepts files up to 50MB each, optionally grouped into an album.
 */
export const uploadMedia = (args: { files: ReadonlyArray<File>; albumName?: string | null }, options?: UploadOptions): Effect.Effect<ReadonlyArray<FileInfo>, ZynkError, ZynkClient> =>
  callUpload("upload_media", args.files, { album_name: args.albumName }, Schema.Array(FileInfo), options)

// ============ Static Files ============

/**
 * Download a static sample file by filename.
 */
export const downloadSampleUrl = (args: { filename?: string }): Effect.Effect<string, never, ZynkClient> =>
  buildStaticUrl("download_sample", { filename: args.filename })

// ============ WebSockets ============

export interface ChatServerEvents {
  chat_message: ChatMessage
  status: ServerStatus
  typing: TypingIndicator
  user_joined: UserJoined
  user_left: UserLeft
}

export interface ChatClientEvents {
  chat_message: ChatMessage
  join: UserJoined
  leave: UserLeft
  typing: TypingIndicator
}

export interface ChatSocket {
  readonly socket: WebSocket
  send<K extends keyof ChatClientEvents>(event: K, data: ChatClientEvents[K]): Effect.Effect<void, ZynkNetworkError>
  on<K extends keyof ChatServerEvents>(event: K): Stream.Stream<ChatServerEvents[K], ZynkNetworkError>
  close: Effect.Effect<void>
}

/**
 * Real-time chat WebSocket endpoint.
 * 
 * Supports:
 * - Sending and receiving chat messages
 * - Typing indicators
 * - Join/leave notifications
 * - Server status updates
 */
export const connectChat = (): Effect.Effect<ChatSocket, ZynkNetworkError, ZynkClient> =>
  Effect.gen(function* () {
    const ws = yield* openWebSocket("chat")
    return {
      socket: ws,
      send<K extends keyof ChatClientEvents>(event: K, data: ChatClientEvents[K]) {
        return Effect.try({
          try: () => ws.send(JSON.stringify({ event, data })),
          catch: (cause) =>
            new ZynkNetworkError({ url: ws.url, cause }),
        })
      },
      on<K extends keyof ChatServerEvents>(event: K) {
        return Stream.async<ChatServerEvents[K], ZynkNetworkError>((emit) => {
          const listener = (ev: MessageEvent) => {
            try {
              const parsed = JSON.parse(ev.data) as { event: string; data: unknown }
              if (parsed.event === event) {
                void emit.single(parsed.data as ChatServerEvents[K])
              }
            } catch (cause) {
              void emit.fail(new ZynkNetworkError({ url: ws.url, cause }))
            }
          }
          ws.addEventListener("message", listener)
          return Effect.sync(() => ws.removeEventListener("message", listener))
        })
      },
      close: Effect.sync(() => ws.close()),
    }
  })
